### ISSUE TITLE
EPIC: Create website

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#1]
The product owner wants to get a stronger online presence by having a website.

## User stories

Owner:
- [x] https://github.com/NiclO1337/pp4-banana-palace/issues/6
- [x] https://github.com/NiclO1337/pp4-banana-palace/issues/7
- [x] https://github.com/NiclO1337/pp4-banana-palace/issues/8
- [x] https://github.com/NiclO1337/pp4-banana-palace/issues/9
- [x] https://github.com/NiclO1337/pp4-banana-palace/issues/10
- [x] #31 
- [x] #32
- [x] #42 
- [ ] #43 
- [ ] #44 

User:
- [x] https://github.com/NiclO1337/pp4-banana-palace/issues/11
- [x] https://github.com/NiclO1337/pp4-banana-palace/issues/12
- [x] https://github.com/NiclO1337/pp4-banana-palace/issues/13
