### ISSUE TITLE
User story: UX and UI

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#10]
Part of EPIC **Sign in feature** #1

As a **owner** I want **to make sure the website is a good user experience** so that **customers enjoy their visit and wants to return**

## Acceptance Criteria

- AC 1: It is easy and intuitive to navigate the webpage
- AC 2: Visual feedback is given to user at all times when navigating the webpage
- AC 3: When customers make changes to their account or booking, they see confirmation that their action has succeded or failed

## Tasks

- [x] Add hover effects
- [x] Add SUCCESS and ERROR messages based on user CRUD actions
- [x] Make sure design follows standard design convention OR is very easy to understand
- [x] Test the functionality by asking for reviews (deployed version)
