### ISSUE TITLE
User story: Find relevant information on website

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#11]
Part of EPIC **Create website** #1

As a **user** I want **to visit the restaurants website** so that **I can see if I am interested in going there**

## Acceptance Criteria

- AC 1: Given that customers are trying to find information about this restaurant when searching then it should be easy to find
- AC 2: Given that customers find the website when searching then they should find relevant information about restaurants location to see if they can to visit

## Tasks

- [x] Add SEO to make website easy to find
- [x] Add location and contact information to website
- [x] Test the functionality (dev environ)
- [x] Test the functionality (deployed version)
