### ISSUE TITLE
User story: Comply with GDPR

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#15]
Part of EPIC **Sign in feature** #2

As a **owner** I want **users to be able to delete their account and information** so that **we are in compliance with GDPR regulations**

## Acceptance Criteria

- AC 1: Given that user is logged into the website when trying to delete account then they should find a "Delete account" button

## Tasks

- [x] Add Delete button to profile page
- [x] Add full CRUD functionality to logged in user on their own account (request.user)
- [x] Test the functionality (dev environ)
- [x] Test the functionality (deployed version)
