### ISSUE TITLE
User story: Special discounts

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#16]
Part of EPIC **Sign in feature** #2

As a **owner** I want **to be able to give some user accounts special discounts** so that **my friends and family can get better price directly when booking online**

## Acceptance Criteria

- AC 1: Given that a user is marked as "friends and familiy" when logged into the website then they should see that they will be granted a discount upon making a reservation

## Tasks

- [x] Add informationon profile page that is only visible {% if user.has_discount %}
- [x] Test the functionality (dev environ)
- [x] Test the functionality (deployed version)
