### ISSUE TITLE
User story: Log in with password

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#17]
Part of EPIC **Sign in feature** #2

As a **user** I want **to be able to sign in with password** so that **my account is secure**

## Acceptance Criteria

- AC 1: Given that user wants to log into their account when visiting the website then they can log in with a secure password

## Tasks

- [x] Install Django Allauth to project
- [x] Add login to the navbar
- [x] Design login and register pages with password
- [x] Test the functionality (dev environ)
- [x] Test the functionality (deployed version)
