### ISSUE TITLE
User story: Log in with social media

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#18]
Part of EPIC **Sign in feature** #2

As a **user** I want **to be able to sign in with social media** so that **logging in is faster and I do not need to remember so many passwords**

## Acceptance Criteria

- AC 1: Given that user wants a faster and more convenient login method when visiting the website then they can do so with social media account

## Tasks

- [ ] Add functionality to login with different social media sites
- [ ] Test the functionality (dev environ)
- [ ] Test the functionality (deployed version)
