### ISSUE TITLE
User story: Update personal information

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#19]
Part of EPIC **Sign in feature** #2

As a **user** I want **to be able to update my personal information** so that **it can always be accurate when I make my bookings**

## Acceptance Criteria

- AC 1: Given that the user is logged in and on their profile page then they have the option to edit their personal information

## Tasks

- [x] Add edit button and secure with (request.user)
- [x] Make sure current information is auto filled into form fields
- [x] Test the functionality (dev environ)
- [x] Test the functionality (deployed version)
