### ISSUE TITLE
User story: Delete account

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#20]
Part of EPIC **Sign in feature** #2

As a **user** I want **to be able to delete my account** so that **so that I can keep my personal information secure by not sharing it anymore**

## Acceptance Criteria

- AC 1: Given that user does wants to delete their account then they can do so from their profile page by clicking on the "Delete account button"

## Tasks

- [x] Add delete button to the profile page
- [x] Defensive programming, make sure to add extra confirmation before deletion
- [x] Test the functionality (dev environ)
- [x] Test the functionality (deployed version)
