### ISSUE TITLE
User story: Reset password

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#21]
Part of EPIC **Sign in feature** #2

As a **user** I want **to be able to reset my password** so that **I can access my account even if I forget my password**

## Acceptance Criteria

- AC 1: Given that the user has forgotten their password when trying to log in to the website then they have the option to reset their password

## Tasks

- [x] Design reset password page
- [x] Test the functionality (dev environ)
- [x] Test the functionality (deployed version)
