### ISSUE TITLE
User story: Reduce admin costs

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#22]
Part of EPIC **Reserve a table** #3

As a **owner** I want **users to be able to book a table online** so that **it reduces our administration costs for handling bookings**

## Acceptance Criteria

- AC 1: Given that a user is logged in when visiting the website then are able to reserve a table on selected date and time

## Tasks

- [x] Add reservation app in project
- [x] Create reservation model according to ERD
- [x] Design the reservation page
- [x] Test the functionality (dev environ)
- [x] Test the functionality (deployed version)
