### ISSUE TITLE
User story: See all reservations

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#23]
Part of EPIC **Reserve a table** #3

As a **owner** I want **it to be able to see all current bookings** so that **we can plan ahead regarding space, table placements and purchasing raw materials**

## Acceptance Criteria

- AC 1: Given that logged in owner has permissions correct permissions then they are able to see all current bookings on the reservation page

## Tasks

- [x] Give owner special permission 
- [x] Adjust reservation page to display all bookings {% if user.has_perm("...") %}
- [x] Test the functionality (dev environ)
- [x] Test the functionality (deployed version)
