### ISSUE TITLE
User story: Online reservation

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#24]
Part of EPIC **Reserve a table** #3

As a **user** I want **to be able to book a table online** so that **booking will be easier and faster than with phone or email**

## Acceptance Criteria

- AC 1: Given that the user is logged into the webpage when clicking on the "Make reservation" button then they are able to make a reservation
- AC 2: Given that user is not logged in when clicking on the "Make reservation" button then they are prompted to first log in or register an account

## Tasks

- [x] Create a button on navbar that leads to reservation page
- [x] Create conditional view based on if user.is_authenticated
- [x] Test the functionality (dev environ)
- [x] Test the functionality (deployed version)
