### ISSUE TITLE
User story: See my current bookings

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#25]
Part of EPIC **Reserve a table** #3

As a **user** I want **to be able to see all my bookings** so that **I can be reminded of when I made the reservations for**

## Acceptance Criteria

- AC 1: Given that the user is logged in when going to the profile page then they are able to see a list of all current bookings that they made

## Tasks

- [x] Display all of users current bookings on their profile page
- [x] Test the functionality (dev environ)
- [x] Test the functionality (deployed version)
