### ISSUE TITLE
User story: Edit bookings

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#26]
Part of EPIC **Reserve a table** #3

As a **user** I want **to be able to edit my current bookings** so that **I can I can have flexibility incase my schedule changes**

## Acceptance Criteria

- AC 1: Given that logged in user has atleast one booking then they can edit it on their profile page

## Tasks

- [x] Add edit button next to bookings
- [x] Make sure form is pre populated with current information
- [x] Display success or error message upon submitting
- [x] Test the functionality (dev environ)
- [x] Test the functionality (deployed version)
