### ISSUE TITLE
User story: Standing reservation

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#28]
Part of EPIC **Reserve a table** #3

As a **user** I want **to be able to make standing reservation** so that **I do not have to make reservation manually every time for regular visits (weekly, monthly or annual reservation)**

## Acceptance Criteria

- AC 1: Given that user is logged in when attempting to make a booking then they see an option to make booking into a weekly/monthly or annual reservation

## Tasks

- [ ] Add functionality to reservation page to make it repeat automatically
- [ ] Test the functionality (dev environ)
- [ ] Test the functionality (deployed version)
