### ISSUE TITLE
User story: Display menu

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#29]
Part of EPIC **Menu** #4 

As a **owner** I want **to show our current menu online** so that **we can attract customers and increace efficiency by reducing the time it takes users to decide what to eat**

## Acceptance Criteria

- AC 1: Given that user click on "Menu" button on the navigation bar then they are able to see the restaurants menu

## Tasks

- [x] Create menu app and add link on navbar
- [x] Design menu page
- [x] Test the functionality (dev environ)
- [x] Test the functionality (deployed version)
