### ISSUE TITLE
User story: Edit menu

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#30]
Part of EPIC **Menu** #4

As a **owner** I want **be able to edit our menu online** so that **it is easy to keep it current and updated**

## Acceptance Criteria

- AC 1: Given that owner needs to update the menu then they are able to edit the menu page

## Tasks

- [x] Add conditional logic so that owner has permissions to edit menu
- [x] Option 1 if time permits, add each menu item to database 
- [ ] Option 2 if short on time, add complete menu to one editable (richtext) form field instead.
- [x] Test the functionality (dev environ)
- [x] Test the functionality (deployed version)
