### ISSUE TITLE
User story: title

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#33]
Part of EPIC **Reserve a table** #3 

As a **owner** I want **to have a reservation page** so that **customers are able to make online reservations**

## Acceptance Criteria

- AC 1: Given that a user visits our webpage, when clicking the button "Make reservation" then they are redirected to the reservation page.

## Tasks

- [ ] Create reservation app
- [ ] Create model for database
- [ ] Design reservation page
- [ ] Test the functionality (dev environ)
- [ ] Test the functionality (deployed version)
