### ISSUE TITLE
User story: Share experiences

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#34]
Part of EPIC **Reviews** #5 

As a **owner** I want **customers to be able to share their experiences** so that **other customers are encouraged to come and improve our restaurant from the feedback**

## Acceptance Criteria

- AC 1: Customer reviews are displayed on the webpage

## Tasks

- [ ] Create review app
- [ ] Create model for database according to ERD
- [ ] Design review page
- [ ] Test the functionality (dev environ)
- [ ] Test the functionality (deployed version)
