### ISSUE TITLE
User story: Owner comments

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#35]
Part of EPIC **Reviews** #5

As a **owner** I want **want to be able to comment on users reviews** so that **I can respond to any feedback**

## Acceptance Criteria

- AC 1: Given that atleast one review has been made, when owner is logged in then they are able to comment on each review

## Tasks

- [ ] Create comment model in review app according to erd
- [ ] Design review page for comments and give owner CRUD permissions
- [ ] Test the functionality (dev environ)
- [ ] Test the functionality (deployed version)
