### ISSUE TITLE
User story: Approve reviews

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#36]
Part of EPIC **Reviews** #5

As a **owner** I want **to be able to approve new and edited reviews** so that **I can make sure posted review follows our rules and guidelines**

## Acceptance Criteria

- AC 1: Given that reviews have been made, when owner is looking at review page then he is able to choose to display it

## Tasks

- [ ] Set owner to have permission to approve reviews
- [ ] Design page to show "approve button" for users with special permission
- [ ] Test the functionality (dev environ)
- [ ] Test the functionality (deployed version)
