### ISSUE TITLE
User story: Delete reviews 

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#37]
Part of EPIC **Reviews** #5

As a **owner** I want **to be able to delete reviews** so that **no inappropriate reviews are shown on the website**

## Acceptance Criteria

- AC 1: Given that there are atleast one review made, when owner is logged in they can delete reviews that they deem inappropriate

## Tasks

- [ ] Add delete button to display if user has permission
- [ ] Give owner permission to delete reviews
- [ ] Test the functionality (dev environ)
- [ ] Test the functionality (deployed version)
