### ISSUE TITLE
User story: Read reviews

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#39]
Part of EPIC **Reviews** #5

As a **user** I want **to see other peoples reviews** so that **I know what previous customers thought about their experience**

## Acceptance Criteria

- AC 1: When visiting the website the user can read reviews from other customers

## Tasks

- [ ] Display reviews on the website
- [ ] Test the functionality (dev environ)
- [ ] Test the functionality (deployed version)
