### ISSUE TITLE
User story: See current users

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#40]
Part of EPIC **Sign in feature** #2

As a **owner** I want **to be able to see a list of all current users** so that **I can find their information and grant some people special "friends and family" discount**

## Acceptance Criteria

- AC 1: Given that owner is logged in, when looking at their profile page then they will see a list of all current users and be able to grant them special discount

## Tasks

- [x] Edit profile page to look different for owner
- [x] Create a button to give discounts to some customers
- [x] Test the functionality (dev environ)
- [x] Test the functionality (deployed version)
