### ISSUE TITLE
User story: Find information about menu

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#41]
Part of EPIC **Menu** #4 

As a **user** I want **to look at the restaurants menu** so that **I can see if I am interested in going there**

## Acceptance Criteria

- AC 1: Given that customers find the website when searching then they should find the restaurants menu to see if they want to visit

## Tasks

- [x] Add menu page and link to navbar
- [x] Test the functionality (dev environ)
- [x] Test the functionality (deployed version)
