### ISSUE TITLE
User story: Picture of food

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#42]
Part of EPIC **Create website** #1

As a **owner** I want **to show images of our menu items in a stylish way** so that **customers will get peckish when they visit the website**

## Acceptance Criteria

- AC 1: Given that a user visits the website when they are on the landing page then they are greeted with images of delicios dishes

## Tasks

- [x] Add images of the dishes on the landing page with name of the dish under it
- [x] Option 1 if time permits, use images from database in current menu items
- [ ] Option 2, link each image directly from Cloudinary
- [x] Test the functionality (dev environ)
- [x] Test the functionality (deployed version)
