### ISSUE TITLE
User story: Click images to make larger

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#43]
Part of EPIC **Create website** #1

As a **owner** I want **to be able to display images larger when clicked** so that **we can display small stylish photos on website but customer can still see all details better if desired**

## Acceptance Criteria

- AC 1: When an image on the website is clicked then a larger version of the same image is displayed

## Tasks

- [ ] Add functionality to display large image when clicked
- [ ] Test the functionality (dev environ)
- [ ] Test the functionality (deployed version)
