### ISSUE TITLE
User story: Dynamic image display

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#44]
Part of EPIC **Create website** #1

As a **owner** I want **images on welcome screen to show in random order** so that **it feels different everytime a customer visits instead of always the same**

## Acceptance Criteria

- AC 1: When the index page is reloaded then images should appear in a different order.

## Tasks

- [ ] Add functionality to randomise the order of images.
- [ ] Test the functionality (dev environ)
- [ ] Test the functionality (deployed version)
