### ISSUE TITLE
User story: Menu item images

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#54]
Part of EPIC **epic** #1

As a **owner** I want **our home page to show all current menu items** so that **customers can see all of our dishes** instead of just our signature dishes

## Acceptance Criteria

- AC 1: Given that a user want to see images of all menu items when browsing the webside then they are able to see all of them on the home page in the carousel

## Tasks

- [ ] Set up Cloudinary to host images remotely
- [ ] Swap carousel to finisedh template carousel-database-items.html
- [ ] Test the functionality (dev environ)
- [ ] Test the functionality (deployed version)
