### ISSUE TITLE
User story: Limit user bookings per account

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#56]
Part of EPIC **Reserve a table** #3

As a **owner** I want **to limit the users ability to make multiple reservations per day** so that **we do not get multiple tables reserved by the same user**

## Acceptance Criteria

- AC 1: Given that a user already have a reservation on the selected date when making another reservation then they should not be able to complete this new reservation and instead be informed that they should call the restaurant to discuss their needs.

## Tasks

- [ ] Limit reserve_table view to check request.users current reservations
- [ ] Redirect to account page if reservation is found on selected date
- [ ] Give the user a message informing them that only 1 reservation is allowed per customer per day and that they should call if they have a party of more than 8 members
- [ ] Test the functionality (dev environ)
- [ ] Test the functionality (deployed version)
