### ISSUE TITLE
User story: Start project

### ISSUE THREAD

**Issue by NiclO1337** [NiclO1337/pp4-banana-palace#6]
Part of EPIC **Create website** #1 

As a **owner** I want **to have website** so that **our restaurant has a stronger online presence and can attract more customers**

## Acceptance Criteria

- AC 1: Given that customers want to find us when searching online then they find our website

## Tasks

- [x] Clone repo and create viritual environment
- [x] Create Django project named banana_palace
- [x] Create home app to be the index.html
- [x] Create base template with header and navbar, and footer 
- [x] Create static files and link in base templates 
- [x] Link also to bootstrap and jquery and font awesome
- [x] Design index page as wireframes
- [x] Test the functionality (dev environ)
- [x] Deploy to heroku
- [x] Test the functionality (deployed version)
